import streamlit as st

from modules.config import configure_page
configure_page()

from modules.ui_components import load_css
load_css()

st.set_page_config(
    page_title="Data Dictionary",
    page_icon="📚",
    layout="wide"
)

st.title("📚 Airline Data Dictionary")

st.markdown("""
This reference guide explains the key airline metrics,
financial KPIs, operational indicators, and sustainability measures
used throughout the Airline Executive Analytics Platform.
""")

st.markdown("---")

# ============================
# COMMERCIAL METRICS
# ============================

st.header("💰 Commercial Metrics")

col1, col2 = st.columns(2)

with col1:

    st.info("""
    **Revenue**

    Total airline revenue generated from ticket sales and ancillary services.
    """)

    st.info("""
    **Profit**

    Revenue minus operating costs.
    """)

    st.info("""
    **Profit Margin**

    Percentage of revenue retained as profit.

    Formula:
    Profit ÷ Revenue × 100
    """)

    st.info("""
    **Revenue Per Passenger**

    Average revenue generated per passenger.
    """)

with col2:

    st.info("""
    **Passenger Yield**

    Revenue generated per passenger kilometre flown.
    """)

    st.info("""
    **RASK**

    Revenue per Available Seat Kilometre.

    Formula:
    Revenue ÷ ASK
    """)

    st.info("""
    **Market Share**

    Percentage of total market traffic captured by the airline.
    """)

st.markdown("---")

# ============================
# OPERATIONS
# ============================

st.header("🛫 Operations Metrics")

col1, col2 = st.columns(2)

with col1:

    st.info("""
    **OTP (On-Time Performance)**

    Percentage of flights departing or arriving within
    15 minutes of scheduled time.
    """)

    st.info("""
    **Delay Rate**

    Percentage of flights experiencing delays.
    """)

with col2:

    st.info("""
    **Cancellation Rate**

    Percentage of scheduled flights cancelled.
    """)

    st.info("""
    **Completion Rate**

    Percentage of flights successfully operated.
    """)

st.markdown("---")

# ============================
# PASSENGERS
# ============================

st.header("👥 Passenger Metrics")

col1, col2 = st.columns(2)

with col1:

    st.info("""
    **Passengers**

    Total number of transported passengers.
    """)

    st.info("""
    **Occupancy**

    Percentage of available seats occupied.
    """)

with col2:

    st.info("""
    **Load Factor**

    Ratio of passengers carried to available seats.

    Formula:
    Passengers ÷ Available Seats × 100
    """)

    st.info("""
    **Passenger Growth**

    Percentage increase in passenger traffic over time.
    """)

st.markdown("---")

# ============================
# FLEET
# ============================

st.header("🛩️ Fleet Metrics")

col1, col2 = st.columns(2)

with col1:

    st.info("""
    **Aircraft Utilization**

    Average flying hours per aircraft.
    """)

    st.info("""
    **Fuel Efficiency**

    Distance flown per unit of fuel consumed.
    """)

with col2:

    st.info("""
    **CASM**

    Cost per Available Seat Kilometre.

    Formula:
    Operating Cost ÷ ASK
    """)

    st.info("""
    **Fuel Burn**

    Total fuel consumption in litres.
    """)

st.markdown("---")

# ============================
# SUSTAINABILITY
# ============================

st.header("🌿 Sustainability Metrics")

col1, col2 = st.columns(2)

with col1:

    st.info("""
    **CO₂ Emissions**

    Total carbon emissions generated by flights.
    """)

with col2:

    st.info("""
    **CO₂ Per Passenger**

    Average emissions generated per passenger.
    """)

st.markdown("---")

# ============================
# FORECASTING
# ============================

st.header("📈 Forecasting Metrics")

st.info("""
**Forecast Revenue**

Predicted future airline revenue based on historical trends.

**Forecast Profit**

Projected future profitability.

**Forecast Passengers**

Expected passenger demand.

**Forecast OTP**

Predicted future on-time performance.

Forecasts are generated using machine learning models and historical airline performance data.
""")

st.markdown("---")

st.success("""
This platform combines commercial, operational, fleet,
passenger, sustainability and forecasting analytics
into a single executive decision-support environment.
""")